### ISSUE TITLE
Error creating iree runtime is causing regression test failures

### ISSUE THREAD

**Issue by not-jenni** [iree-org/iree-samples#70]
https://github.com/iree-org/iree-samples/runs/7789826451?check_suite_focus=true

```I0811 15:09:43.843804 139964147017536 test_util.py:82] Setting up iree runtime
[  FAILED  ] AlbertTest.test_compile_tflite
======================================================================
ERROR: test_compile_tflite (__main__.AlbertTest)
AlbertTest.test_compile_tflite
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/iree-samples/iree-samples/tflitehub/albert_test.py", line 30, in test_compile_tflite
    self.compile_and_execute()
  File "/home/runner/work/iree-samples/iree-samples/tflitehub/test_util.py", line 129, in compile_and_execute
    self.setup_iree()
  File "/home/runner/work/iree-samples/iree-samples/tflitehub/test_util.py", line 86, in setup_iree
    vm_module = iree_rt.VmModule.from_flatbuffer(f.read())
TypeError: from_flatbuffer(): incompatible function arguments. The following argument types are supported:
    1. (arg0: iree._runtime.VmInstance, arg1: object) -> iree._runtime.VmModule

Invoked with: b'PK\x03\x04-\x00\x00\x00\x00\x00\x00\x00!\x00

**Comment by ScottTodd** [comment]
Probably need to update that test util after https://github.com/iree-org/iree/pull/10017

> The python `VmModule.from_flatbuffer` signature has been changed to take `(vm_instance, file)`.

That PR has a few examples of how to update Python code

**Comment by not-jenni** [comment]
That fixed the tests, thanks for pointing this out @ScottTodd !
