### ISSUE TITLE
Error invoking iree-compile is causing regression test failures

### ISSUE THREAD

**Issue by not-jenni** [iree-org/iree-samples#82]
https://github.com/iree-org/iree-samples/actions/runs/3826764148/jobs/6510806357

```
ERROR: test_compile_tflite (__main__.MobilenetV2Uint8Test)
MobilenetV2Uint8Test.test_compile_tflite
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/iree-samples/iree-samples/tflitehub/mobilenet_v2_uint8_test.py", line 27, in test_compile_tflite
    self.compile_and_execute()
  File "/home/runner/work/iree-samples/iree-samples/tflitehub/test_util.py", line 120, in compile_and_execute
    iree_tflite_compile.compile_file(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/iree/compiler/tools/tflite.py", line 154, in compile_file
    result = invoke_pipeline([import_cl, compile_cl])
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/iree/compiler/tools/binaries.py", line 259, in invoke_pipeline
    raise CompilerToolError(stage.completed)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
```

mobilenet_v1_uint8_test, mobilenet_v2_uint8_test, and mobilenet_v3-large_uint8_test are impacted

**Comment by jpienaar** [comment]
These are passing with latest nightly.
